config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

    get 'relationships/:id/follows' => 'public/relationships#follows', as: "relationships_follows"
    get 'relationships/:id/followers' => 'public/relationships#followers', as: "relationships_followers"
    
    get 'users/posts' => 'public/posts#new'
    post 'users/posts' => 'public/posts#create'
    get 'users/posts/edit/:id' => 'public/posts#edit', as: "users_posts_edit"
    patch 'users/posts/edit/:id' => 'public/posts#update'
    get 'users/posts/:id' => 'public/posts#show', as: "users_posts_show"
    delete 'users/posts/:id' => 'public/posts#destroy', as: "destroy_posts"

    get 'users/:id' => 'public/users#show', as: "users_show"
    get 'users/:id/edit' => 'public/users#edit', as: "users_edit"
    patch 'users/:id/edit' => 'public/users#update'
    get 'users/:id/withdraw_confirm' => 'public/users#withdraw_confirm', as: "users_withdraw"
    patch 'users/:id/withdraw_confirm' => 'public/users#withdraw'
    
    get 'users/:id/follows' => 'public/users#follows', as: "follows"
    get 'users/:id/followers' => 'public/users#followers', as: "followers"
    delete 'users/:user_id/relationships' => 'public/relationships#destroy', as: "relationships"
    post 'users/:user_id/relationships' => 'public/relationships#create'

   

    post 'users/posts/:id/comments' => 'public/comments#create', as: "posts_comments"
    delete 'users/posts/:id/comments' => 'public/comments#destroy', as: "destroy_posts_comments"



    root to: 'public/homes#top'

  namespace :admin do
    resources :users, only: [:show, :edit, :update]
  end
  namespace :admin do
    get 'homes' => 'homes#top'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  layout "admin_application"
  def top
    @users = User.all.search(params[:search])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div>
<h1 class="page_title" style="width:200px;">会員一覧</h1>

<div style="margin-left:800px;">
      <%= form_with url: admin_homes_path, method: :get do %>
      <%= text_field_tag :search %>
      <%= submit_tag '検索', name: nil %>
      <% end %>
</div>
    
</div>
    
  <div class="admin_user_all">
    <table border="3" style="border-collapse: collapse; width:60%; background-color:white;">
      <thead>
        <tr>
          <th style="width:5%" bgcolor="gray">ID</th>
          <th style="width:20%" bgcolor="gray">ニックネーム</th>
          <th style="width:35%" bgcolor="gray">メールアドレス</th>
        </tr>
      </thead>
      <tbody>
         <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td>
            <%= link_to edit_admin_user_path(user.id) do %>
            <%= user.name %>
            <% end %>
          </td>
          <td><%= user.email %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
  