config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

    get 'relationships/:id/follows' => 'public/relationships#follows', as: "relationships_follows"
    get 'relationships/:id/followers' => 'public/relationships#followers', as: "relationships_followers"
    
    get 'users/posts' => 'public/posts#new'
    post 'users/posts' => 'public/posts#create'
    get 'users/posts/edit/:id' => 'public/posts#edit', as: "users_posts_edit"
    patch 'users/posts/edit/:id' => 'public/posts#update'
    get 'users/posts/:id' => 'public/posts#show', as: "users_posts_show"
    delete 'users/posts/:id' => 'public/posts#destroy', as: "destroy_posts"

    get 'users/:id' => 'public/users#show', as: "users_show"
    get 'users/:id/edit' => 'public/users#edit', as: "users_edit"
    patch 'users/:id/edit' => 'public/users#update'
    get 'users/:id/withdraw_confirm' => 'public/users#withdraw_confirm', as: "users_withdraw"
    patch 'users/:id/withdraw_confirm' => 'public/users#withdraw'
    
    get 'users/:id/follows' => 'public/users#follows', as: "follows"
    get 'users/:id/followers' => 'public/users#followers', as: "followers"
    delete 'users/:user_id/relationships' => 'public/relationships#destroy', as: "relationships"
    post 'users/:user_id/relationships' => 'public/relationships#create'

   

    post 'users/posts/:id/comments' => 'public/comments#create', as: "posts_comments"
    delete 'users/posts/:id/comments' => 'public/comments#destroy', as: "destroy_posts_comments"



    root to: 'public/homes#top'

  namespace :admin do
    resources :users, only: [:show, :edit, :update]
  end
  namespace :admin do
    get 'homes' => 'homes#top'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         

         has_one_attached :profile

        has_many :posts
        has_many :comments
        
        has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
        has_many :follow, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
        
        has_many :follow_user, through: :follower, source: :follow # 自分がフォローしている人
        has_many :follower_user, through: :follow, source: :follower # 自分をフォローしている人
        
 


        def follow(user_id)
          follower.create!(follow_id: user_id)
        end
      
        # ユーザーのフォローを外す
        def unfollow(user_id)
          follower.find_by(follow_id: user_id).destroy
        end
      
        # フォローしていればtrueを返す
        def follow?(user)
          follow_user.include?(user)
        end

        enum play_time: { '平日昼間': 0, '平日夜間': 1, '土日昼間': 2, '土日夜間': 3, '不定期': 4 }
        
        def self.search(search)
          search ? where('name LIKE ?', "%#{search}%") : all
        end
        


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  layout "admin_application"
  def show
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_homes_path
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:is_active)
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<h1 class="page_title">会員情報編集画面</h1>

<%= form_with model: @user, url: admin_user_path, method: :patch do |f| %>
  
  <table border="2" class="admin_edit_table">

  <tr>
    <th>ニックネーム</th>
  　<td><%= @user.name %></td>
  </tr>

  <tr>
    <th>年齢</th>
  　<td><%= @user.age %>歳</td>
  </tr>
  
  <tr>
    <th>メールアドレス</th>
    <td><%= @user.email %></td>
  </tr>
  
  <tr>
    <th>よく遊ぶゲーム</th>
  　<td><%= @user.game_title %></td>
  </tr>
  
  <tr>
    <th>会員ステータス</th>
    
  　<td>
      <%= f.radio_button :is_active, "true" %>
      <%= f.label :is_active, "会員" %>
      <%= f.radio_button :is_active, "false" %>
      <%= f.label :is_active, "退会" %>
    </td>
  </tr>

  </table>

  <div class="actions" style="margin:20px 0; text-align:center;">
    <input type="submit" value="保存" class="admin_edit_button">
  </div>
<% end %>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>
<p>Find me in app/views/admin/users/show.html.erb</p>