config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

    get 'relationships/:id/follows' => 'public/relationships#follows', as: "relationships_follows"
    get 'relationships/:id/followers' => 'public/relationships#followers', as: "relationships_followers"
    
    get 'users/posts' => 'public/posts#new'
    post 'users/posts' => 'public/posts#create'
    get 'users/posts/edit/:id' => 'public/posts#edit', as: "users_posts_edit"
    patch 'users/posts/edit/:id' => 'public/posts#update'
    get 'users/posts/:id' => 'public/posts#show', as: "users_posts_show"
    delete 'users/posts/:id' => 'public/posts#destroy', as: "destroy_posts"

    get 'users/:id' => 'public/users#show', as: "users_show"
    get 'users/:id/edit' => 'public/users#edit', as: "users_edit"
    patch 'users/:id/edit' => 'public/users#update'
    get 'users/:id/withdraw_confirm' => 'public/users#withdraw_confirm', as: "users_withdraw"
    patch 'users/:id/withdraw_confirm' => 'public/users#withdraw'
    
    get 'users/:id/follows' => 'public/users#follows', as: "follows"
    get 'users/:id/followers' => 'public/users#followers', as: "followers"
    delete 'users/:user_id/relationships' => 'public/relationships#destroy', as: "relationships"
    post 'users/:user_id/relationships' => 'public/relationships#create'

   

    post 'users/posts/:id/comments' => 'public/comments#create', as: "posts_comments"
    delete 'users/posts/:id/comments' => 'public/comments#destroy', as: "destroy_posts_comments"



    root to: 'public/homes#top'

  namespace :admin do
    resources :users, only: [:show, :edit, :update]
  end
  namespace :admin do
    get 'homes' => 'homes#top'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GamerConnection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header style="background-color:black;">
      
        <div class="header_tag">
          
          <nav>
            <ul>
              <li>
                <b><%= link_to "Topへ", admin_homes_path, style: "text-decoration: none; color:black;" %></b>
              </li>
              
              <li>
                <b><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, style: "text-decoration: none; color:black;" %></b>
              </li>
                
            </ul>
          </nav>
      </div>
        
        <div class="header-text" style="text-align:center;">Gamer Connection</div>
        
      
    </header>
    <%= yield %>
    
    <footer>
        <div class="footer_area">
          
        </div>
        
      </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GamerConnection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="body_size">
    
    <header class="header_image">
      
        <div class="header_tag">
          <%= link_to root_path do %>
            <%= image_tag'logo_new.png', size: "120x100"%>
          <% end %>
          
          <nav>
            <ul>
              <% if user_signed_in? %>
              <li>
                <b><%= link_to "マイページ", users_show_path(current_user.id), style: "text-decoration: none; color:black;" %></b>
              </li>
              
              <li>
                <b><%= link_to "新規投稿", users_posts_path, style: "text-decoration: none; color:black;" %></b>
              </li>
              
              <li>
                <b><%= link_to "ログアウト", destroy_user_session_path, method: :delete, style: "text-decoration: none; color:black;" %></b>
              </li>
                
              
              <% else %>
              <li>
                <b><%= link_to "新規登録", new_user_registration_path, style: "text-decoration: none; color:black;" %></b>
              </li>
              
              <li>
                <b><%= link_to "ログイン", new_user_session_path, style: "text-decoration: none; color:black;" %></b>
              </li>
              
              <li>
                <b><%= link_to "投稿一覧", root_path, style: "text-decoration: none; color:black;" %></b>
              </li>
              
              <% end %>
            </ul>
          </nav>
      </div>
      
      <div class="header-center">
        
        <div class="header-text">Gamer Connection</div>
        
        </div>
      
    </header>
    
    <div class="left-side-bar">
  
        <table border="2" class="rank_table">
          <td colspan="2">ゲームランキング</td>
          <% rank_num = 1 %>
            <% Post.find(Post.group(:game_name).order('count(game_name) desc').limit(5).pluck(:id)).each.with_index(1) do |post, i| %>
            <% if post.nil? %>
              <tr>
                <th>第<%= rank_num %>位</th>
              　<td></td>
              </tr>
              
            <% else %>
              <tr>
                <th>第<%= rank_num %>位</th>
              　<td><%= post.game_name %></td>
              </tr>
            <% end %>
        
                <% rank_num += 1 %>
            <% end %>
        
        </table>
              
      </div>
      
      <div class="right-side-bar">
          <div style="margin-top:50px;">
            <%= form_with url: root_path, method: :get do %>
              <%= text_field_tag :search %>
              <%= submit_tag '検索', name: nil %>
            <% end %>
          </div>
          
          <div style="color:white; text-align:center; text-size:10px; margin-top:50px;">
            ニンテンドー公式サイトは 
            <a href="https://www.nintendo.co.jp/index.html" title="https://www.nintendo.co.jp/index.html" style="background-color:white; text-decoration:none;">
              こちら
            </a>
          </div>
          
          <div style="color:white; text-align:center; text-size:10px; margin-top:10px;">
            playstation公式サイトは 
            <a href="https://www.playstation.com/ja-jp/" title="https://www.playstation.com/ja-jp/" style="background-color:white; text-decoration:none;">
              こちら
            </a>
          </div>
          
      </div>
    <%= yield %>
    
    <footer>
        <div class="footer_area">
          <div style="color:white; text-align:center;">Logo made by <a href="https://www.designevo.com/" title="Free Online Logo Maker">DesignEvo free logo creator</a></div>
        </div>
        
      </footer>
      
    </div>

  </body>
</html>